### PR TITLE
Product listing page

### PR DESCRIPTION
**Pull request by Pratik1005**
Added all product cards and filter section

### CODE REVIEW

**Review by shraddha15-creator — CHANGES_REQUESTED** [review]
Hey your sidebar is going over the footer when we scroll down. Try to fix it

**Comment by Pratik1005** [comment]
on desktop view or mobile view?

**Comment by shraddha15-creator** [comment]
> 

On desktop

Screenshot 2022-02-12 200432

**Comment by shraddha15-creator** [comment]
> > 
> 
> On desktop
> 
> Screenshot 2022-02-12 200432

Is it working fine for you?

**Comment by Pratik1005** [comment]
yes...I'm not able to see this sidebar issue on my desktop.. still I'll check again.

**Comment by shraddha15-creator** [comment]
> yes...I'm not able to see this sidebar issue on my desktop.. still I'll check again.

Oh then I think this might be happening because of deploy preview.

**Review by JowelTisso — APPROVED** [review]

**Review by ayush65 — APPROVED** [review]

**Comment by Pratik1005** [comment]
hey shraddha I have fixed the sidebar pls can you have a look.

**Comment by shraddha15-creator** [comment]
> hey shraddha I have fixed the sidebar pls can you have a look.

Yes, it's fixed now. Looking good.

**Review by shraddha15-creator — APPROVED** [review]

**Comment by Pratik1005** [comment]
Tysm for pointing out the bug

**Pull request merged**
